### ISSUE TITLE
Working on 2017

### ISSUE THREAD

**Issue by melMass** [sideeffects/HoudiniEngineForMaya#7]
Just to tell you it does compile on maya 2017 OSX.

**Comment by crydalch** [comment]
Yes it would be good to note this in the ReadMe, and mention it's the Qt5 flavor that are supported, not Qt4.

**Comment by davvid** [comment]
FYI pull request #8 adds support for Maya 2018 as well.

**Comment by andrewkww** [comment]
Updated the outdated README in c0b956be2a93c910bdf745e627f48c149c1be799.

@crydalch: The Maya plugin should work regardless of Qt version. The Maya plugin (and Houdini Engine) shouldn't be pulling in any of the Qt dependencies.

@davvid: Since we can't provide the binaries for Maya 2018 yet, I didn't include Maya 2018 into the list of supported versions.
